export const FLAG_GETTING_USERS = 'FLAG_GETTING_USERS';
export const GET_USERS_SUCCEEDED = 'GET_USERS_SUCCEEDED';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';
export const GET_USERS = 'GET_USERS';
export const FLAG_GETTING_CURRENT_USER = 'FLAG_GETTING_CURRENT_USER';
export const GET_CURRENT_USER_SUCCEEDED = 'GET_CURRENT_USER_SUCCEEDED';
export const GET_CURRENT_USER_FAILED = 'GET_CURRENT_USER_FAILED';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
